
title: Python Level 0
email: eric.busboom@jointheleague.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
#theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-toc

toc:
   min_level: 1
   max_level: 3
   list_class: toc
   list_class: toc__list
   sublist_class: toc__sublist

# For the tasks.py tasks
tasks:
  module_source: null # This is the source of the module files, usually set via ENV Var
