base: /Level0/
description: description
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /images/Flag.png
  nav:
  - link: /guide/
    text: Guide
  - link: /config/
    text: Config
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /lessons
    title: Introduction
  - children:
      - path: /lessons/lesson1/meet-tina-the-turtle/
        title: Meet Tina the Turtle
      - path: /lessons/lesson1/shapes-and-colors/
        title: Shapes and Colors
    collapsable: false
    title: lesson1
  - children:
    - path: /lessons/lesson2/flaming-ninja-star/
      title: Flaming Ninja Star
    - path: /lessons/lesson2/turtle-spiral/
      title: Turtle Spiral
    collapsable: false
    title: lesson2

title: League Level0 Python
